<?php
include('dbconn.php');
session_start();

// Include PHPMailer
require 'PHPMAILER/vendor/autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// Function to send the management code email
function sendManagementCodeEmail($email, $managementCode, $firstname, $lastname, $position) {
    $mail = new PHPMailer(true);
    try {
        $mail->isSMTP();
        $mail->Host = 'smtp.hostinger.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'TheHiveResidences@swarmthehive.online';
        $mail->Password = 'G#pdFHa7i';
        $mail->SMTPSecure = 'tls';
        $mail->Port = 587;
        $mail->setFrom('TheHiveResidences@swarmthehive.online', 'SWARM - The Hive Residences');

        $mail->addAddress($email);
        $mail->isHTML(true);
        $mail->Subject = 'Welcome to The Hive Residences - Management Portal Access';

        // Create HTML email template
        $loginUrl = "https://swarmthehive.online/management-index.php";
        
        $emailBody = '
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 5px;">
            <div style="text-align: center; margin-bottom: 20px;">
                <img src="https://swarmthehive.online/img/logo%20swarm.png" alt="SWARM Logo" style="max-width: 150px;">
                <h1 style="color: #F6BE00;">Welcome to The Hive Residences Management</h1>
            </div>
            
            <div style="margin-bottom: 25px;">
                <p>Dear ' . $firstname . ' ' . $lastname . ',</p>
                <p>Welcome to The Hive Residences management team! Your account has been successfully created.</p>
                <p>Your position: <strong>' . $position . '</strong></p>
                <p>Your management code is provided below. Please keep this code for your records:</p>
                
                <div style="text-align: center; margin: 25px 0;">
                    <div style="background-color: #f5f5f5; padding: 15px; border-radius: 5px; font-size: 24px; font-weight: bold; letter-spacing: 5px;">
                        ' . $managementCode . '
                    </div>
                </div>
                
                <p>Please click the button below to access the management portal:</p>
                
                <div style="text-align: center; margin: 25px 0;">
                    <a href="' . $loginUrl . '" style="background-color: #F6BE00; color: #000; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block;">Access Management Portal</a>
                </div>
                
                <p>If the button above doesn\'t work, you can copy and paste the following link into your browser:</p>
                <p><a href="' . $loginUrl . '">' . $loginUrl . '</a></p>
            </div>
            
            <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #777; font-size: 12px;">
                <p>This is an automated message. Please do not reply to this email.</p>
                <p>&copy; ' . date('Y') . ' The Hive Residences. All rights reserved.</p>
            </div>
        </div>
        ';

        $mail->Body = $emailBody;
        $mail->AltBody = "Welcome to The Hive Residences Management! Your management code is: $managementCode. Please visit $loginUrl to access the management portal.";

        $mail->send();
        return true;
    } catch (Exception $e) {
        return false;
    }
}

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $firstname = $_POST["firstname"];
    $middlename = $_POST["middlename"];
    $lastname = $_POST["lastname"];
    $contact_number = $_POST["contact_number"];
    $email = $_POST["email"];
    $position = $_POST["position"];
    $security_number = !empty($_POST["security_number"]) ? $_POST["security_number"] : null;
    $shift_schedule = !empty($_POST["shift_schedule"]) ? $_POST["shift_schedule"] : null;
    $password = $_POST["password"];

    // Hash the password before inserting into the database
    $hashedPassword = password_hash($password, PASSWORD_DEFAULT);
    
    // Prepare SQL statement - let the database triggers handle the Management_Code
    $sql = "INSERT INTO managementaccount 
        (firstname, middlename, lastname, contact_number, email, position, security_number, shift_schedule, password) 
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

    $stmt = $conn->prepare($sql);
    $stmt->bind_param("sssssssss", $firstname, $middlename, $lastname, $contact_number, $email, $position, $security_number, $shift_schedule, $hashedPassword);

    if ($stmt->execute()) {
        // Get the last inserted ID and Management_Code
        $newUserId = $conn->insert_id;
        
        // Query to get the Management_Code that was generated by the trigger
        $codeQuery = "SELECT Management_Code FROM managementaccount WHERE Management_ID = ?";
        $codeStmt = $conn->prepare($codeQuery);
        $codeStmt->bind_param("i", $newUserId);
        $codeStmt->execute();
        $codeStmt->bind_result($managementCode);
        $codeStmt->fetch();
        $codeStmt->close();
        
        // Send the management code email
        $emailSent = sendManagementCodeEmail($email, $managementCode, $firstname, $lastname, $position);
        
        if ($emailSent) {
            $_SESSION['message'] = "Registration Successful! Management code has been sent to your email.";
        } else {
            $_SESSION['message'] = "Registration Successful! However, failed to send the email with management code.";
        }
        $_SESSION['message_type'] = "success";
    } else {
        $_SESSION['message'] = "Error: " . $stmt->error;
        $_SESSION['message_type'] = "error";
    }

    $stmt->close();
    $conn->close();

    // Redirect to avoid form resubmission
    header("Location: management-index.php");
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Swarm | Management Registration</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        primary: '#e9be3a',
                        secondary: '#2c3e50',
                        accent: '#3498db',
                        danger: '#e74c3c',
                        success: '#2ecc71',
                        neutral: '#f8f9fa',
                        'neutral-focus': '#e9ecef'
                    },
                    fontFamily: {
                        'sans': ['Inter', 'sans-serif']
                    },
                    boxShadow: {
                        'card': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
                        'button': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)'
                    }
                }
            }
        }
    </script>
    <style>
        /* Additional custom styles */
        .form-input-focus:focus {
            box-shadow: 0 0 0 3px rgba(233, 190, 58, 0.2);
        }
    </style>
</head>

<body class="bg-neutral min-h-screen flex items-center justify-center p-6 font-sans">
    <!-- Background pattern -->
    <div class="fixed inset-0 bg-gradient-to-br from-neutral to-white z-0 opacity-70"></div>
    
    <!-- Main content -->
    <div class="relative z-10 w-full max-w-2xl my-8">
        <div class="bg-white rounded-xl shadow-card p-8 border border-gray-100">
            <!-- Header and logo -->
            <div class="text-center mb-6">
                <div class="flex justify-center mb-4">
                    <img src="./img/logo swarm.png" class="h-14" alt="Swarm Logo">
                </div>
                <h1 class="text-2xl font-semibold text-secondary mb-1">Management Registration</h1>
                <p class="text-gray-500 text-sm">Complete the form to create a new management account</p>
            </div>
            
            <!-- Success/Error Messages -->
            <?php if (isset($_SESSION['message'])): ?>
                <?php if ($_SESSION['message_type'] === 'success'): ?>
                    <div class="bg-green-50 border-l-4 border-success text-success px-4 py-3 rounded mb-6">
                        <div class="flex items-center">
                            <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
                            </svg>
                            <span><?php echo $_SESSION['message']; ?></span>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="bg-red-50 border-l-4 border-danger text-danger px-4 py-3 rounded mb-6">
                        <div class="flex items-center">
                            <svg class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                                <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"></path>
                            </svg>
                            <span><?php echo $_SESSION['message']; ?></span>
                        </div>
                    </div>
                <?php endif; ?>
                <?php unset($_SESSION['message']); unset($_SESSION['message_type']); ?>
            <?php endif; ?>
            
            <!-- Registration Form -->
            <form method="POST" action="ManagementRegistration.php" class="mt-4">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                    <!-- First Name -->
                    <div>
                        <label for="firstname" class="block text-sm font-medium text-gray-700 mb-1">First Name</label>
                        <input 
                            type="text" 
                            id="firstname" 
                            name="firstname" 
                            required
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                    </div>
                    
                    <!-- Middle Name -->
                    <div>
                        <label for="middlename" class="block text-sm font-medium text-gray-700 mb-1">Middle Name (Optional)</label>
                        <input 
                            type="text" 
                            id="middlename" 
                            name="middlename"
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                    </div>
                    
                    <!-- Last Name -->
                    <div>
                        <label for="lastname" class="block text-sm font-medium text-gray-700 mb-1">Last Name</label>
                        <input 
                            type="text" 
                            id="lastname" 
                            name="lastname" 
                            required
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                    </div>
                    
                    <!-- Contact Number -->
                    <div>
                        <label for="contact_number" class="block text-sm font-medium text-gray-700 mb-1">Contact Number</label>
                        <input 
                            type="text" 
                            id="contact_number" 
                            name="contact_number" 
                            required
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                    </div>
                    
                    <!-- Email Address -->
                    <div class="md:col-span-2">
                        <label for="email" class="block text-sm font-medium text-gray-700 mb-1">Email Address</label>
                        <input 
                            type="email" 
                            id="email" 
                            name="email" 
                            required
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                    </div>
                    
                    <!-- Position -->
                    <div>
                        <label for="position" class="block text-sm font-medium text-gray-700 mb-1">Position</label>
                        <select 
                            id="position" 
                            name="position" 
                            onchange="toggleFields()" 
                            required
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                            <option value="">Select Position</option>
                            <option value="Finance">Finance</option>
                            <option value="Security">Security</option>
                            <option value="Maintenance">Maintenance</option>
                            <option value="Admin">Admin</option>
                            <option value="Property Manager">Property Manager</option>
                        </select>
                    </div>
                    
                    <!-- Password -->
                    <div>
                        <label for="password" class="block text-sm font-medium text-gray-700 mb-1">Password</label>
                        <input 
                            type="password" 
                            id="password" 
                            name="password" 
                            required
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                    </div>
                    
                    <!-- Security Number (Hidden by default) -->
                    <div id="security_number_field" class="hidden">
                        <label for="security_number" class="block text-sm font-medium text-gray-700 mb-1">Security Number</label>
                        <input 
                            type="text" 
                            id="security_number" 
                            name="security_number"
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                    </div>
                    
                    <!-- Shift Schedule (Hidden by default) -->
                    <div id="shift_schedule_field" class="hidden">
                        <label for="shift_schedule" class="block text-sm font-medium text-gray-700 mb-1">Shift Schedule</label>
                        <input 
                            type="text" 
                            id="shift_schedule" 
                            name="shift_schedule"
                            class="form-input-focus w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:border-primary transition-colors"
                        >
                    </div>
                </div>
                
                <!-- Register Button -->
                <div class="mt-8">
                    <button 
                        type="submit" 
                        class="w-full py-2.5 px-4 bg-primary hover:bg-opacity-90 text-white font-medium rounded-lg transition-all duration-200 shadow-button flex items-center justify-center"
                    >
                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 9v3m0 0v3m0-3h3m-3 0h-3m-2-5a4 4 0 11-8 0 4 4 0 018 0zM3 20a6 6 0 0112 0v1H3v-1z"></path>
                        </svg>
                        <span>Complete Registration</span>
                    </button>
                </div>
                
                <!-- Back to Login Link -->
                <div class="mt-4 text-center">
                    <a href="management-index.php" class="text-primary hover:underline text-sm font-medium transition-colors">
                        Back to Login
                    </a>
                </div>
            </form>
            
            <!-- Footer -->
            <div class="mt-8 text-center text-xs text-gray-500">
                <p>© 2025 Swarm</p>
            </div>
        </div>
    </div>
    
    <script>
        function toggleFields() {
            let position = document.getElementById("position").value;
            let securityNumberField = document.getElementById("security_number_field");
            let shiftScheduleField = document.getElementById("shift_schedule_field");

            if (position === "Finance") {
                securityNumberField.classList.add("hidden");
                shiftScheduleField.classList.add("hidden");
            } else if (position === "Security") {
                securityNumberField.classList.remove("hidden");
                shiftScheduleField.classList.remove("hidden");
            } else if (position === "Maintenance") {
                securityNumberField.classList.add("hidden");
                shiftScheduleField.classList.remove("hidden");
            } else if (position === "Admin") {
                securityNumberField.classList.add("hidden");
                shiftScheduleField.classList.add("hidden");
            } else if (position === "Property Manager") {
                securityNumberField.classList.add("hidden");
                shiftScheduleField.classList.add("hidden");
            } else {
                securityNumberField.classList.add("hidden");
                shiftScheduleField.classList.add("hidden");
            }
        }
    </script>
</body>
</html>